#pragma config(Motor,  port2,           claw_motor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left_speed = 0;
int right_speed = 0;

void control() {
	left_speed = 0;
	right_speed = 0;
	int speed_input = vexRT[Ch1];
	int direction_input = vexRT[Ch2];
	left_speed = left_speed + speed_input;
	right_speed = right_speed + speed_input;

	if (direction_input < 0) {
		left_speed = left_speed + abs(direction_input);
	}
	if (direction_input > 0) {
		right_speed = right_speed + abs(direction_input);
	}

	motor(left_motor) = left_speed;
	motor(right_motor) = right_speed;
}

task main()
{
	while (true) {
		control();
	}
}
