#pragma config(Motor,  port2,           claw_motor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right_motor,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left_motor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float sensitivity = 1.5;

void control() {
	motor(left_motor) = vexRT[Ch1] * sensitivity;
	motor(right_motor) = vexRT[Ch3] * sensitivity;
}

task main() {
	while (true) {
		control();
	}
}
