#pragma config(Sensor, dgtl11, debug_button,   sensorTouch)
#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           back_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           back_right,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           left_arm_a,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           right_arm_a,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right_arm_b,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left_arm_b,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/////////////////////////////// CONFIG //////////////////////////////////
int frame = 0;
float CONFIG_control_adjust = 0.01;
float CONFIG_precise_ratio = 2.5;
float CONFIG_slow_rate = 0.01;
float CONFIG_slow_tick = 30;
float CONFIG_drive_mode = 1;
float CONFIG_accel_tick = 200;
float CONFIG_turn_ratio = 0.75;
float ARM_up_speed = 60;
float ARM_down_speed = 40;
float ARM_hover_speed = 100;
int LCD_left_button = 1;
int LCD_center_button = 2;
int LCD_right_button = 4;
int LCD_refresh_rate = 30;
float CONTROL_sensitivity = 1.2;
float CONTROL_threshold = 2;
float CONTROL_min_speed = 5;
float CONTROL_precise = CONTROL_sensitivity / CONFIG_precise_ratio;
int CONTROL_direction = 1;
int CONTROL_precise_toggle = 0;

float left = 0;
float right = 0;
float acceleration_left = 0;
float acceleration_right = 0;

float prev_left = 0;
float prev_right = 0;

float debug_one = 0;
float debug_two = 0;

/////////////////////////////// MISC ////////////////////////////////////
int onezeroneg(float val) {
	if (val < 0) {return -1;}
	else if (val > 0) {return 1;}
	else {return 0;}
}
bool ontick(int tick) {
	return (frame%tick == 0);
}

/////////////////////////////// MOVEMENT ////////////////////////////////
void MOVEMENT_left_drive(float power) {
	motor(front_left) = power;
	motor(back_left) = power;
}
void MOVEMENT_right_drive(float power) {
	motor(front_right) = power;
	motor(back_right) = power;
}
void MOVEMENT_drive(float pl, float pr, float time) {
	MOVEMENT_left_drive(pl);
	MOVEMENT_right_drive(pr);
	wait1Msec(time);
	MOVEMENT_left_drive(0);
	MOVEMENT_right_drive(0);
}

/////////////////////////////// ARM CODE ////////////////////////////////
void ARM_up() {
	motor[left_arm_a] = ARM_up_speed;
	motor[right_arm_a] = ARM_up_speed;
	motor[left_arm_b] = ARM_up_speed;
	motor[right_arm_b] = ARM_up_speed;
}
void ARM_stop() {
	motor[left_arm_a] = 20;
	motor[right_arm_a] = 20;
	motor[left_arm_b] = 20;
	motor[right_arm_b] = 20;
}
void ARM_down() {
	motor[left_arm_a] = -ARM_down_speed;
	motor[right_arm_a] = -ARM_down_speed;
	motor[left_arm_b] = -ARM_down_speed;
	motor[right_arm_b] = -ARM_down_speed;
}
void ARM_coast() {
	motor[left_arm_a] = 0;
	motor[right_arm_a] = 0;
	motor[left_arm_b] = 0;
	motor[right_arm_b] = 0;
}
void ARM_move(float direction, float time) {
	if (direction < 0) {
		ARM_down();
	} else if (direction > 0) {
		ARM_up();
	} else {
		ARM_coast();
	}
	wait1Msec(time);
	ARM_stop();
}

/////////////////////////////// LCD SETUP ///////////////////////////////
void displayLCDFloat(int line, int pos, float val) {
	clearLCDLine(line);
	string valstr = val;
	displayLCDString(line, pos, valstr);
}
void LCD_init() {
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
}
/////////////////////////////// STATES //////////////////////////////////
bool STATE_LCD_voltage() {
	return (nLCDButtons == LCD_left_button || SensorValue[debug_button] || vexRT[Btn5D]);
}
bool STATE_LCD_sensitivity() {
	return (nLCDButtons == LCD_right_button || vexRT[Btn8R]);
}
bool STATE_adjust_sensdown() {
	return (STATE_LCD_sensitivity() && vexRT[Btn7D]);
}
bool STATE_adjust_sensup() {
	return (STATE_LCD_sensitivity() && vexRT[Btn7R]);
}
bool STATE_adjust_threshdown() {
	return (STATE_LCD_sensitivity() && vexRT[Btn7L]);
}
bool STATE_adjust_threshup() {
	return (STATE_LCD_sensitivity() && vexRT[Btn7U]);
}
bool STATE_precise_control() {
	if (vexRT[Btn8D]) {
		if (CONTROL_precise_toggle == 1) {
			CONTROL_precise_toggle = 0;
		} else {
			CONTROL_precise_toggle = 1;
		}
		wait1Msec(200);
	}
	return ((bool)CONTROL_precise_toggle);
}

bool STATE_toggle_drive_mode() {
	return (vexRT[Btn7U] == 1);
}
bool STATE_view_speed() {
	return (onezeroneg(left) || onezeroneg(right));
}
bool STATE_ARM_up() {
	return ((bool)vexRT[Btn6U]);
}
bool STATE_ARM_down() {
	return ((bool)vexRT[Btn6D]);
}
bool STATE_debug_view() {
	return ((bool)vexRT[Btn7D]);
}

/////////////////////////////// LCD VIEWS ///////////////////////////////
void VIEW_blank() {
	clearLCDLine(0);
	clearLCDLine(1);
}
void VIEW_voltage() {
	float voltage = nImmediateBatteryLevel/1000.0;
	displayLCDString(0, 0, "Battery voltage: ");
	displayLCDFloat(1, 0, voltage);
}
void VIEW_sensitivity() {
	displayLCDFloat(0, 0, CONTROL_threshold);
	displayLCDFloat(1, 0, CONTROL_sensitivity);
}
void VIEW_info() {
	VIEW_blank();
	displayLCDString(0, 0, "Driver mode");
	if (STATE_precise_control()) {
		displayLCDString(1, 0, "PRECISE");
	} else {
		clearLCDLine(1);
	}
	if (CONFIG_drive_mode) {
		displayLCDString(0, 15, "E");
	} else {
		displayLCDString(0, 15, "L");
	}
}
void VIEW_leftright() {
	displayLCDFloat(0, 0, left);
	displayLCDFloat(1, 0, right);
}
void VIEW_debug() {
	displayLCDFloat(0, 0, debug_one);
	displayLCDFloat(1, 0, debug_two);
}

/////////////////////////////// DO TASKS ////////////////////////////////
void DO_lcd() {
	if (ontick(LCD_refresh_rate)) {
		if (STATE_LCD_voltage()) {
			VIEW_voltage();
		} else if (STATE_LCD_sensitivity()) {
			VIEW_sensitivity();
		} else if (STATE_view_speed()) {
			VIEW_leftright();
		} else if (STATE_debug_view()) {
			VIEW_debug();
		} else {
			VIEW_info();
		}
	}
}
void DO_usercontrol() {
	left = vexRT[Ch3];
	right = vexRT[Ch2];
	if (CONFIG_drive_mode == 1) {
		left = ((left*left*left)/20000);
		right = ((right*right*right)/20000);
	}
	left = left * CONTROL_sensitivity;
	right = right * CONTROL_sensitivity;
	if (left > -CONTROL_threshold && left < CONTROL_threshold) {
		left = 0;
	}
	if (right > -CONTROL_threshold && right < CONTROL_threshold) {
		right = 0;
	}
	left = left + (onezeroneg(left) * CONTROL_min_speed);
	right = right + (onezeroneg(right) * CONTROL_min_speed);
}
void DO_senscontrol() {
	if (ontick(50)) {
		if (STATE_adjust_sensup()) {
			CONTROL_sensitivity = CONTROL_sensitivity + CONFIG_control_adjust;
		}
		if (STATE_adjust_sensdown()) {
			CONTROL_sensitivity = CONTROL_sensitivity - CONFIG_control_adjust;
		}
		if (STATE_adjust_threshup()) {
			CONTROL_threshold = CONTROL_threshold + CONFIG_control_adjust;
		}
		if (STATE_adjust_threshdown()) {
			CONTROL_threshold = CONTROL_threshold - CONFIG_control_adjust;
		}
	}
}
void DO_precisecontrol() {
	if (ontick(CONFIG_slow_tick) && ! STATE_LCD_sensitivity()) {
		if (STATE_precise_control()) {

			if (CONTROL_sensitivity > CONTROL_precise) {
				CONTROL_sensitivity = CONTROL_sensitivity - CONFIG_slow_rate;
			}
		} else {
			if (CONTROL_sensitivity < CONTROL_precise * CONFIG_precise_ratio) {
				CONTROL_sensitivity = CONTROL_sensitivity + CONFIG_slow_rate;
			}
		}
	}
	if (STATE_toggle_drive_mode()) {
		if (CONFIG_drive_mode == 1) {
			CONFIG_drive_mode = 0;
		} else {
			CONFIG_drive_mode = 1;
		}
		wait1Msec(2);
	}
}
void DO_calcs() {
	if (ontick(CONFIG_accel_tick)) {
		acceleration_left = prev_left - left;
		acceleration_right = prev_right - right;

		prev_left = left;
		prev_right = right;
	}
}
void DO_movement() {
	if (STATE_precise_control()) {
		DO_precisecontrol();
	}
	int r = CONTROL_direction * right;
	int l = CONTROL_direction * left;
	if ((l < 0 && r > 0) || ( l > 0 && r < 0)) {
		l = l * CONFIG_turn_ratio;
		r = r * CONFIG_turn_ratio;
	}
	MOVEMENT_left_drive(l);
	MOVEMENT_right_drive(r);
}

void DO_arm() {
	if (STATE_ARM_up()) {
		ARM_up();
	}
	else if (STATE_ARM_down()) {
		ARM_down();
	} else {
		ARM_stop();
	}
}

void DO_auton() {
	MOVEMENT_drive(-70, -70, 800);			//Back
	MOVEMENT_drive(60, 60, 1100);				//Forwards
	ARM_move(1, 1500);									//Raise stars
	MOVEMENT_drive(0, -70, 1150);				//Turn
	MOVEMENT_drive(50, 50, 50);					//Halt
	MOVEMENT_drive(-50, -50, 1650);			//Drive to fence
	ARM_move(1, 1650);									//Flip over fence
	ARM_move(-1, 2500);									//Lower arm
	ARM_move(0, 700);										//Coast arm
	MOVEMENT_drive(50, 50, 1000);				//Drive forwards
	MOVEMENT_drive(50, -50, 500);				//Turn to middle
	MOVEMENT_drive(40, 40, 1400);				//Drive to stars
	ARM_move(1, 1200);
	MOVEMENT_drive(-40, -40, 1400);
	MOVEMENT_drive(-50, 50, 400);
	MOVEMENT_drive(-50, -50, 1000);
	ARM_move(1, 1200);
	ARM_move(-1, 2000);
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  bDisplayCompetitionStatusOnLcd = false;
  LCD_init();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous() {
	//Drive back
	//Arm down
	//Drive forward
	//Arm up half way
	//Drive to fence
	//Arm up and over fence
	//Arm down
	//Forwards
	displayLCDString(0, 0, "AUTONOMOUS MODE");
	DO_auton();
	LCD_init();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol() {
	DO_auton();
	while (true) {
		DO_lcd();
		DO_usercontrol();
		DO_precisecontrol();
		DO_calcs();
		DO_movement();
		DO_arm();
		DO_senscontrol();

		frame++;
	}
}
