#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           front_right,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           back_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           back_right,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void left_drive(int power) {
	motor(front_left) = power;
	motor(back_left) = power;
}

void right_drive(int power) {
	motor(front_right) = power;
	motor(back_right) = power;
}

task main() {
	right_drive(100);
	left_drive(100);
	wait1Msec(1000);
	right_drive(0);
	left_drive(0);
}
