#pragma config(Motor,  port2,           front_left,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           front_right,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           back_left,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           back_right,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void left_drive(int power) {
	motor(front_left) = power;
	motor(back_left) = power;
}

void right_drive(int power) {
	motor(front_right) = power;
	motor(back_right) = power;
}

task main() {
	//dostuff
}
