#pragma config(Sensor, dgtl1,  debug_button,   sensorTouch)
#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           front_right,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           back_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           back_right,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           recovery_servo, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int LCD_left_button = 1;
int LCD_center_button = 2;
int LCD_right_button = 4;

float left_move = 0;
float right_move = 0;

int recovery_servo_pos = 0;

float control_sensitivity = 0.8;
float control_threshold = 13.5;

int LCD_selected = 1;
int frame = 0;

//void displayLCDInt(int line, int pos, int val) {
//	clearLCDLine(line);
//	string valstr = val;
//	displayLCDString(line, pos, valstr);
//}

void displayLCDFloat(int line, int pos, float val) {
	clearLCDLine(line);
	string valstr = val;
	displayLCDString(line, pos, valstr);
}

void initLCD() {
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
}

void left_drive(float power) {
	motor(front_left) = power;
	motor(back_left) = power;
}

void right_drive(float power) {
	motor(front_right) = power;
	motor(back_right) = power;
}

void DO_wheelmovement() {
	left_move = vexRT[Ch3];
	right_move = vexRT[Ch2];
	if (left_move > -control_threshold && left_move < control_threshold) {
		left_move = 0;
	}
	if (right_move > -control_threshold && right_move < control_threshold) {
		right_move = 0;
	}
	left_drive(left_move * control_sensitivity);
	right_drive(right_move * control_sensitivity);
}

void DO_lcd() {
	if (frame%5 == 0) {
		if (vexRT[Btn5D] || SensorValue[debug_button]) {
			displayLCDString(0, 0, "Battery voltage: ");
			displayLCDFloat(1, 0, nImmediateBatteryLevel/1000.0);
		} else {
			displayLCDFloat(0, 0, control_threshold);
			displayLCDFloat(1, 0, control_sensitivity);
		}
	}
}

void DO_lcdsenscontrol() {
	if (frame%50 == 0) {
		if (nLCDButtons == LCD_center_button) {
			if (LCD_selected == 1) {
				LCD_selected = 2;
			} else {
				LCD_selected = 1;
			}
			wait1Msec(100);
		}
		if (nLCDButtons == LCD_right_button) {
			if (LCD_selected == 1) {
				control_sensitivity = control_sensitivity + 0.01;
			} else if (LCD_selected == 2) {
				control_threshold = control_threshold + 0.01;
			}
		}
		if (nLCDButtons == LCD_left_button) {
			if (LCD_selected == 1) {
				control_sensitivity = control_sensitivity - 0.01;
			} else if (LCD_selected == 2) {
				control_threshold = control_threshold - 0.01;
			}
		}
	}
}

void DO_remotesenscontrol() {
	if (frame%50 == 0 && vexRT[Btn5U]) {
		if (vexRT[Btn7U]) {
			control_threshold = control_threshold + 0.01;
		}
		if (vexRT[Btn7L]) {
			control_threshold = control_threshold - 0.01;
		}
		if (vexRT[Btn7R]) {
			control_sensitivity = control_sensitivity + 0.01;
		}
		if (vexRT[Btn7D]) {
			control_sensitivity = control_sensitivity - 0.01;
		}
	}
}

void DO_recoveryservo() {
	if (frame%100 == 0) {
		if (vexRT[Btn7U]) {
			recovery_servo_pos++;
		}
		if (vexRT[Btn7L]) {
			recovery_servo_pos--;
		}
		motor(recovery_servo) = recovery_servo_pos;
	}
}

task main() {
	initLCD();
	while (true) {
		DO_wheelmovement();
		DO_lcd();
		DO_lcdsenscontrol();
		DO_remotesenscontrol();
		DO_recoveryservo();

		frame++;
	}
}
