#pragma config(Motor,  port2,           front_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           front_right,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           back_left,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           back_right,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           left_arm,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           right_arm,     tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void left_drive(float power) {
	motor(front_left) = power;
	motor(back_left) = power;
}

void right_drive(float power) {
	motor(front_right) = power;
	motor(back_right) = power;
}

void arm_up(float speed) {
	motor[left_arm] = speed;
	motor[right_arm] = speed;
}

void arm_stop() {
	motor[left_arm] = 0;
	motor[right_arm] = 0;
}

void arm_down(float speed) {
	motor[left_arm] = -speed;
	motor[right_arm] = -speed;
}

int onezeroneg(float val) {
	if (val < 0) {return -1;}
	else if (val > 0) {return 1;}
	else {return 0;}
}

task main()
{
	int left, right;
	float sensitivity = 1.2;
	float threshold = 10;
	float min_speed = 5;
	float arm_up_speed = 50;
	float arm_down_speed = 50;
	while (true) {
		left = vexRT[Ch3];
		right = vexRT[Ch2];
		left = ((left*left*left)/20000);
		right = ((right*right*right)/20000);
		left = left * sensitivity;
		right = right * sensitivity;
		if (left > -threshold && left < threshold) {
			left = 0;
		}
		if (right > -threshold && right < threshold) {
			right = 0;
		}
		left_drive(left + (onezeroneg(left) * min_speed));
		right_drive(right + (onezeroneg(right) * min_speed));
		if (vexRT[Btn6U]) {arm_up(arm_up_speed);}
		else if (vexRT[Btn5U]) {arm_down(arm_down_speed);}
		else {arm_stop();}
	}
}
