#pragma config(Sensor, in3,    pot,            sensorPotentiometer)
#pragma config(Sensor, in4,    pot2,           sensorPotentiometer)
#pragma config(Motor,  port7,           mot,           tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float X = 0;


task main()
{
	turn_to(0, 40, mot, pot);
}
