#pragma config(Motor,  port2,           claw_motor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           right_motor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           arm_motor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           left_motor,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor(right_motor) = 50;
	motor(left_motor) = -50;
	wait1Msec(900);
	motor(right_motor) = 0;
	motor(left_motor) = 0;
}
