#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port6,           main_motor,    tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int posn;

task main()
{
	while (true) {
		//motor(main_motor) = 30;
		resetMotorEncoder(main_motor);
		wait1Msec(1000);
		posn = getMotorEncoder(main_motor);
	}
}
