#pragma config(Motor,  port2,           amotor,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true) {
		motor(amotor) = vexRT[Ch2];
	}
}
