#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  afront,         sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int dist;
string sdist;

void LCD_reset() {
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
}

task main()
{
	LCD_reset();
	while (true) {
		dist = SensorValue[afront];
		sprintf(sdist, "%f", dist);
		displayLCDString(0, 0, sdist);
		wait1Msec(250);
	}
}
